### ISSUE TITLE
Unable to use `svp login` with github

### ISSUE THREAD

**Issue by swichers** [jelmer/silver-platter#27]
Trying to login results in the following error:

```sh
~/d/repos ❯❯❯ /home/<snip>/.local/bin/svp login https://github.com
GitHub username: <snip>
HTTPS <snip>@github.com password:
Traceback (most recent call last):
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/plugins/github/cmds.py", line 47, in run
    authorization = user.create_authorization(
  File "/usr/lib/python3/dist-packages/github/AuthenticatedUser.py", line 464, in create_authorization
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 286, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<snip>/.local/bin/svp", line 8, in <module>
    sys.exit(main())
  File "/home/<snip>/.local/lib/python3.9/site-packages/silver_platter/__main__.py", line 137, in main
    return subcommands[args.subcommand](rest)
  File "/home/<snip>/.local/lib/python3.9/site-packages/silver_platter/__main__.py", line 72, in login_main
    return cmd_gh.run()
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/commands.py", line 782, in run
    return class_run(*args, **kwargs)
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/plugins/github/cmds.py", line 56, in run
    raise errors.CommandError(e.data['message'])
breezy.errors.CommandError: Not Found
```

I tried username, e-mail address, password, PAT w/ limited access, PAT w/ full access, PAT as the username and no pass, no user and PAT only. Also tried with and without a trailing slash per the example.

Weirdly, changing `https://github.com` to `http://github.com` does get different output:

```sh
~/d/repos ❯❯❯ /home/<snip>/.local/bin/svp login http://github.com
Please visit http://github.com/-/profile/personal_access_tokens to obtain a private token.
Please visit http://github.com/-/profile/personal_access_tokens to obtain a private token.
Private token:
Traceback (most recent call last):
  File "/home/<snip>/.local/bin/svp", line 8, in <module>
    sys.exit(main())
  File "/home/<snip>/.local/lib/python3.9/site-packages/silver_platter/__main__.py", line 137, in main
    return subcommands[args.subcommand](rest)
  File "/home/<snip>/.local/lib/python3.9/site-packages/silver_platter/__main__.py", line 66, in login_main
    return cmd_gl.run(args.url)
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/commands.py", line 782, in run
    return class_run(*args, **kwargs)
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/plugins/gitlab/cmds.py", line 76, in run
    store_gitlab_token(name=name, url=url, private_token=private_token)
  File "/home/<snip>/.local/lib/python3.9/site-packages/breezy/plugins/gitlab/hoster.py", line 170, in store_gitlab_token
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<snip>/.config/breezy/gitlab.conf'
```

...but also references gitlab instead of github.

**Comment by swichers** [comment]
```
~/d/repos ❯❯❯ sudo apt install silver-platter -y
~/d/repos ❯❯❯ svp login 'https://github.com'
<snip above>
~/d/repos ❯❯❯ cat /etc/debian_version
11.0
~/d/repos ❯❯❯ pip show breezy
Name: breezy
Version: 3.2.2
Summary: Friendly distributed version control system
Home-page: https://www.breezy-vcs.org/
Author: None
Author-email: None
License: GNU GPL v2
Location: /home/<snip>/.local/lib/python3.9/site-packages
Requires: configobj, fastbencode, patiencediff, dulwich
Required-by: silver-platter
```

**Comment by jelmer** [comment]
This is fixed in the upcoming breezy >= 3.3; let me see if I can release that in the next couple of days.

**Comment by jelmer** [comment]
What version of breezy are you running?

Jelmer

**Comment by swichers** [comment]
Sorry, I wound up building my own set of scripts to handle this functionality in the mean time. I do not have it or the dependencies installed any longer.
